/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        ink: '#14161F',
        'ink-soft': '#1C1F2C',
        paper: '#EDE6D6',
        'paper-dim': '#B8AF9C',
        stamp: '#B33F3F',
        'stamp-dark': '#8C2F2F',
        brass: '#C99A3D',
        // New UI system colors
        surface: "#16130a",
        "primary-container": "#b33f3f",
        "surface-tint": "#ffb3af",
        "on-error": "#690005",
        tertiary: "#c4c5d6",
        "inverse-surface": "#e9e2d2",
        "tertiary-fixed": "#e0e1f3",
        "surface-variant": "#38352a",
        background: "#16130a",
        "on-surface-variant": "#debfbd",
        "on-tertiary-fixed": "#181b27",
        "tertiary-fixed-dim": "#c4c5d6",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#5e4200",
        "secondary-fixed": "#ffdea7",
        "surface-container-highest": "#38352a",
        "on-primary-fixed-variant": "#871f22",
        "surface-container": "#222016",
        "on-tertiary": "#2d303d",
        "surface-container-low": "#1e1c12",
        "secondary-fixed-dim": "#f2bf5e",
        "secondary-container": "#886100",
        secondary: "#f2bf5e",
        "on-secondary-fixed": "#271900",
        "on-tertiary-container": "#e3e5f7",
        "surface-bright": "#3c392e",
        "on-surface": "#e9e2d2",
        error: "#ffb4ab",
        "on-primary-fixed": "#410005",
        "on-primary-container": "#ffdfdc",
        "primary-fixed": "#ffdad7",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#434654",
        "surface-dim": "#16130a",
        "on-primary": "#67030f",
        "on-background": "#e9e2d2",
        "surface-container-high": "#2d2a1f",
        "on-secondary": "#412d00",
        "surface-container-lowest": "#100e06",
        "tertiary-container": "#646675",
        "inverse-on-surface": "#333026",
        primary: "#ffb3af",
        "outline-variant": "#574140",
        "on-secondary-container": "#ffe5bb",
        "primary-fixed-dim": "#ffb3af",
        "inverse-primary": "#a83737",
        outline: "#a68a88",
        parchment: "#EDE6D6",
        "ink-black": "#14161F",
        "brand-red": "#B33F3F",
        "brand-brass": "#C99A3D",
        "brand-muted": "#6B6455",
      },
      fontFamily: {
        display: ['"Fraunces"', 'serif'],
        mono: ['"Space Mono"', 'monospace'],
        body: ['"Inter"', 'sans-serif'],
        // New UI system typography
        "body-md": ["Libre Franklin"],
        "display-lg": ["EB Garamond"],
        "label-mono": ["Space Mono"],
        "body-sm": ["Libre Franklin"],
        "stamp-lg": ["Space Mono"],
        "title-sm": ["EB Garamond"],
        "headline-md": ["EB Garamond"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-mono": ["13px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "stamp-lg": ["24px", { lineHeight: "24px", letterSpacing: "0.1em", fontWeight: "700" }],
        "title-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
      },
      spacing: {
        "section-margin": "64px",
        "container-padding": "40px",
        base: "8px",
        "card-gap": "16px",
        gutter: "24px",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      keyframes: {
        thump: {
          '0%': { transform: 'scale(2.2) rotate(-14deg)', opacity: '0' },
          '55%': { transform: 'scale(0.94) rotate(-8deg)', opacity: '1' },
          '75%': { transform: 'scale(1.05) rotate(-10deg)' },
          '100%': { transform: 'scale(1) rotate(-8deg)', opacity: '1' },
        },
      },
      animation: {
        thump: 'thump 0.4s cubic-bezier(0.2, 0.8, 0.3, 1.1) forwards',
      },
    },
  },
  plugins: [],
};
